// <auto-generated />
using System;
using Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(NonStopContext))]
    [Migration("20190608095753_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Name");

                    b.Property<string>("PatronymicName");

                    b.Property<string>("Surname");

                    b.Property<int?>("UnivercityId");

                    b.HasKey("Id");

                    b.HasIndex("UnivercityId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Application.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<int?>("UnivercityId");

                    b.HasKey("Id");

                    b.HasIndex("UnivercityId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Application.Models.Univercity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("Univercities");
                });

            modelBuilder.Entity("Application.Models.Person", b =>
                {
                    b.HasOne("Application.Models.Univercity", "Univercity")
                        .WithMany()
                        .HasForeignKey("UnivercityId");
                });

            modelBuilder.Entity("Application.Models.Specialization", b =>
                {
                    b.HasOne("Application.Models.Univercity")
                        .WithMany("Specializations")
                        .HasForeignKey("UnivercityId");
                });
#pragma warning restore 612, 618
        }
    }
}
